# Generated by Django 4.2.5 on 2023-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="full_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
