# Generated by Django 4.2.5 on 2023-09-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_person_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="full_name",
            new_name="name",
        ),
    ]
